#!/usr/bin/env python3
"""Generate fake rocm-smi output for the card detection.

Why: the numbering logic in lib/llmreg.py has to be right with 1, 2 or 3+ cards
and with an iGPU at any position. Those cases cannot be produced on a single
machine, so we feed the detection output that CAN occur and check the result.

Usage:  python3 tests/fixtures/mk-smi.py            (writes next to this file)
        LLM_FIXTURE_DIR=/tmp/x python3 .../mk-smi.py   (writes there instead)
Used as: LLM_ROCM_SMI=tests/fixtures/rocm-smi-3card.sh python3 lib/llmreg.py gpus

The test harness passes LLM_FIXTURE_DIR so that a test run never rewrites the
committed copies. They regenerate byte-identically today, but the first change
to this file would otherwise dirty the working tree on every run.
"""

import os
import stat

HERE = os.environ.get("LLM_FIXTURE_DIR") or os.path.dirname(os.path.abspath(__file__))

R9700 = {"series": "AMD Radeon AI PRO R9700", "gfx": "gfx1201", "vram": 34208743424}
W7900 = {"series": "AMD Radeon PRO W7900", "gfx": "gfx1100", "vram": 51539607552}
#  An iGPU as rocm-smi reports it: a CPU name and 0.5 GB.
IGPU = {"series": "AMD Ryzen 7 7700X 8-Core Processor", "gfx": "gfx1036",
        "vram": 536870912}
#  An APU carving out a large UMA region - exactly the case where a pure VRAM
#  threshold fails and only the name still helps.
APU_BIG = {"series": "AMD Ryzen 7 8700G w/ Radeon 780M Graphics", "gfx": "gfx1103",
           "vram": 17179869184}

#  An older ROCm that does not answer --showpower or --showuse at all. Not a
#  different card but a different TOOL, so it belongs here as a case rather than
#  being carved out of a generated file with `sed -n '4,$p' | head -n -2`, which
#  is what gpu-matrix used to do and which tied it to the exact number of header
#  and footer lines below.
NO_POWER = {"1card-nopower"}

CASES = {
    "1card":      [R9700],
    "1card-nopower": [R9700],
    "2card":      [R9700, R9700],
    "3card":      [R9700, R9700, R9700],
    "igpu-last":  [R9700, R9700, IGPU],          # what a machine with an iGPU last looks like
    "igpu-first": [IGPU, R9700, R9700],          # the discrete cards then sit at 1,2
    "apu-16gb":   [APU_BIG, R9700],              # threshold does not catch it, the name does
    "mixed":      [R9700, W7900],                # different size and gfx target
    "none":       [],                            # no ROCm, or no permission
}


def render(cards: list[dict], no_power: bool = False) -> str:
    out = ["", "==== ROCm System Management Interface ====", "==== Concise Info ===="]
    for i, c in enumerate(cards):
        used = 171778048 if i == 0 else 73072640
        #  An APU reports its power under a different label than a discrete
        #  card, and the parser is supposed to accept both - so say it the way
        #  the hardware says it.
        socket = c["vram"] < 20 * 1024**3 and "Ryzen" in c["series"]
        out += [
            "GPU[%d]\t\t: Temperature (Sensor edge) (C): 30.0" % i,
            "GPU[%d]\t\t: Temperature (Sensor junction) (C): %.1f" % (i, 29.0 + i),
            "GPU[%d]\t\t: Temperature (Sensor memory) (C): 34.0" % i,
            *([] if no_power else [
                "GPU[%d]\t\t: %s Graphics Package Power (W): %.1f" % (
                    i, "Current Socket" if socket else "Average", 17.0 + i),
                "GPU[%d]\t\t: GPU use (%%): %d" % (i, 0 if i else 42)]),
            "GPU[%d]\t\t: VRAM Total Memory (B): %d" % (i, c["vram"]),
            "GPU[%d]\t\t: VRAM Total Used Memory (B): %d" % (i, used),
            "GPU[%d]\t\t: Card Series: \t\t%s" % (i, c["series"]),
            "GPU[%d]\t\t: Card Model: \t\t0x7551" % i,
            "GPU[%d]\t\t: GFX Version: \t\t%s" % (i, c["gfx"]),
        ]
    out += ["==== End of ROCm SMI Log ====", ""]
    return "\n".join(out)


for name, cards in CASES.items():
    path = os.path.join(HERE, "rocm-smi-%s.sh" % name)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("#!/bin/sh\n# GENERATED by mk-smi.py - do not edit by hand.\n")
        fh.write("cat <<'SMI'\n%s\nSMI\n" % render(cards, name in NO_POWER))
    os.chmod(path, os.stat(path).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print("  %-28s %d card(s) as rocm-smi would report" % (os.path.basename(path), len(cards)))
