#!/bin/sh
# GENERATED by mk-smi.py - do not edit by hand.
cat <<'SMI'

==== ROCm System Management Interface ====
==== Concise Info ====
GPU[0]		: Temperature (Sensor edge) (C): 30.0
GPU[0]		: Temperature (Sensor junction) (C): 29.0
GPU[0]		: Temperature (Sensor memory) (C): 34.0
GPU[0]		: Current Socket Graphics Package Power (W): 17.0
GPU[0]		: GPU use (%): 42
GPU[0]		: VRAM Total Memory (B): 536870912
GPU[0]		: VRAM Total Used Memory (B): 171778048
GPU[0]		: Card Series: 		AMD Ryzen 7 7700X 8-Core Processor
GPU[0]		: Card Model: 		0x7551
GPU[0]		: GFX Version: 		gfx1036
GPU[1]		: Temperature (Sensor edge) (C): 30.0
GPU[1]		: Temperature (Sensor junction) (C): 30.0
GPU[1]		: Temperature (Sensor memory) (C): 34.0
GPU[1]		: Average Graphics Package Power (W): 18.0
GPU[1]		: GPU use (%): 0
GPU[1]		: VRAM Total Memory (B): 34208743424
GPU[1]		: VRAM Total Used Memory (B): 73072640
GPU[1]		: Card Series: 		AMD Radeon AI PRO R9700
GPU[1]		: Card Model: 		0x7551
GPU[1]		: GFX Version: 		gfx1201
GPU[2]		: Temperature (Sensor edge) (C): 30.0
GPU[2]		: Temperature (Sensor junction) (C): 31.0
GPU[2]		: Temperature (Sensor memory) (C): 34.0
GPU[2]		: Average Graphics Package Power (W): 19.0
GPU[2]		: GPU use (%): 0
GPU[2]		: VRAM Total Memory (B): 34208743424
GPU[2]		: VRAM Total Used Memory (B): 73072640
GPU[2]		: Card Series: 		AMD Radeon AI PRO R9700
GPU[2]		: Card Model: 		0x7551
GPU[2]		: GFX Version: 		gfx1201
==== End of ROCm SMI Log ====

SMI
