#!/bin/sh
# GENERATED by mk-smi.py - do not edit by hand.
cat <<'SMI'

==== ROCm System Management Interface ====
==== Concise Info ====
GPU[0]		: Temperature (Sensor edge) (C): 30.0
GPU[0]		: Temperature (Sensor junction) (C): 29.0
GPU[0]		: Temperature (Sensor memory) (C): 34.0
GPU[0]		: VRAM Total Memory (B): 17179869184
GPU[0]		: VRAM Total Used Memory (B): 171778048
GPU[0]		: Card Series: 		AMD Ryzen 7 8700G w/ Radeon 780M Graphics
GPU[0]		: Card Model: 		0x7551
GPU[0]		: GFX Version: 		gfx1103
GPU[1]		: Temperature (Sensor edge) (C): 30.0
GPU[1]		: Temperature (Sensor junction) (C): 30.0
GPU[1]		: Temperature (Sensor memory) (C): 34.0
GPU[1]		: VRAM Total Memory (B): 34208743424
GPU[1]		: VRAM Total Used Memory (B): 73072640
GPU[1]		: Card Series: 		AMD Radeon AI PRO R9700
GPU[1]		: Card Model: 		0x7551
GPU[1]		: GFX Version: 		gfx1201
==== End of ROCm SMI Log ====

SMI
